apiVersion: rancher.devops.io/v1
kind: Project
metadata:
  name: my-dev-project
spec:
  # Management policies control operator behavior.
  # Default (if omitted): ["Create", "Delete"]
  # 
  # Available policies:
  # - Create: Allows creating projects, namespaces, and members
  # - Delete: Allows deleting projects and removing namespace associations
  # - Observe: Discovers existing namespaces/members in project and adds them to CRD spec
  #
  # Common combinations:
  # - ["Create", "Delete"]: Full management (default)
  # - ["Create"]: Create-only, prevents deletion
  # - ["Observe", "Create", "Delete"]: Take over existing project and fully manage it
  # - ["Observe"]: Read-only discovery, no creation or deletion
  managementPolicies:
    - Create
    - Delete
  
  # Name of the Rancher cluster (not the cluster ID)
  clusterName: "local"
  
  # Display name for the project in Rancher
  displayName: "Development Project"
  
  # Optional description
  description: "Development environment for my application"
  
  # Namespaces to create and link to this project
  namespaces:
    - dev-app
    - dev-database
    - dev-cache
  
  # Project members with their roles
  members:
    # You can specify either principalId directly OR principalName for lookup.
    - principalName: "jdoe"  # Will be resolved to a principal ID
      role: "project-owner"
    - principalId: "local://user-def456"  # Direct ID still works
      role: "project-member"
  
  # Optional resource quotas
  resourceQuota:
    limitsCpu: "10"
    limitsMemory: "20Gi"
    requestsCpu: "2"
    requestsMemory: "4Gi"
